development:
  host: localhost
  adapter: postgresql
  database: sparkposter_development
  username: <%= `whoami` %>

test:
  host: localhost
  adapter: postgresql
  database: sparkposter_test
  username: <%= `whoami` %>

production:
  host: localhost
  adapter: postgresql
  database: sparkposter_production
  username: <%= `whoami` %>
